In [67]:
from keras.datasets import cifar10

In [68]:
#tuple unpacking
(x_train,y_train),(x_test,y_test) = cifar10.load_data()

In [69]:
import matplotlib.pyplot as plt
%matplotlib inline

**NORMALIZATION THROUGH SKLEARN**

from sklearn.preprocessing import MinMaxScaler
#reshaping
n,x,y,c = x_train.shape
x_train = x_train.reshape(50000,x,y,1)

n,x,y,c = x_test.shape
x_test = x_test.reshape(10000,x,y,1)

#normalization
scaler_object = MinMaxScaler()
scaler_object.fit(x_train)
scaled_x_train = scaler_object.transform(x_train)
scaled_x_test = scaler_object.transform(x_test)

In [70]:
#NORMALIZATION
x_train =x_train/255
x_test = x_test/255

In [71]:
#converting the labels using onehot encoding
from keras.utils.np_utils import to_categorical
y_cat_train = to_categorical(y_train,10)
y_cat_test = to_categorical(y_test,10)

In [72]:
from keras.models import Sequential
from keras.layers import Dense,Conv2D,Flatten,MaxPool2D

In [73]:
#MODEL CREATION
model = Sequential()

#ADDING LAYERS
#covolution layer and maxpool layer 
model.add(Conv2D(filters = 32,kernel_size = (4,4),input_shape = (32,32,3),activation ='relu'))
model.add(MaxPool2D(pool_size = (2,2)))

#covolution layer and maxpool layer 
model.add(Conv2D(filters = 32,kernel_size = (4,4),input_shape = (32,32,3),activation ='relu'))
model.add(MaxPool2D(pool_size = (2,2)))

#Flatten
model.add(Flatten())

#DENSE
model.add(Dense(256,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))

#COMPILE THE MODEL
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop',metrics = ['accuracy'])

In [74]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 29, 29, 32)        1568      
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 11, 11, 32)        16416     
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 5, 5, 32)          0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 800)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 256)               205056    
_________________________________________________________________
dense_12 (Dense)             (None, 10)                2570      
Total para

In [75]:
model.fit(x_train,y_cat_train,epochs = 20,verbose = 2)

Epoch 1/20
 - 54s - loss: 1.5244 - acc: 0.4503
Epoch 2/20
 - 54s - loss: 1.1716 - acc: 0.5888
Epoch 3/20
 - 54s - loss: 1.0197 - acc: 0.6444
Epoch 4/20
 - 52s - loss: 0.9180 - acc: 0.6827
Epoch 5/20
 - 53s - loss: 0.8345 - acc: 0.7124
Epoch 6/20
 - 53s - loss: 0.7663 - acc: 0.7374
Epoch 7/20
 - 53s - loss: 0.7120 - acc: 0.7534
Epoch 8/20
 - 65s - loss: 0.6657 - acc: 0.7751
Epoch 9/20
 - 77s - loss: 0.6283 - acc: 0.7872
Epoch 10/20
 - 71s - loss: 0.5918 - acc: 0.8011
Epoch 11/20
 - 75s - loss: 0.5591 - acc: 0.8101
Epoch 12/20
 - 73s - loss: 0.5407 - acc: 0.8165
Epoch 13/20
 - 79s - loss: 0.5144 - acc: 0.8268
Epoch 14/20
 - 76s - loss: 0.4909 - acc: 0.8358
Epoch 15/20
 - 71s - loss: 0.4716 - acc: 0.8430
Epoch 16/20
 - 72s - loss: 0.4571 - acc: 0.8480
Epoch 17/20
 - 70s - loss: 0.4427 - acc: 0.8534
Epoch 18/20
 - 71s - loss: 0.4357 - acc: 0.8586
Epoch 19/20
 - 70s - loss: 0.4202 - acc: 0.8619
Epoch 20/20
 - 76s - loss: 0.4142 - acc: 0.8645


In [76]:
model.evaluate(x_test,y_cat_test)

10000/10000 [==============================] - 8s 802us/step


[1.6838909366607666, 0.6508]

In [77]:
predictions = model.predict_classes(x_test)

In [78]:
from sklearn.metrics import classification_report,confusion_matrix

In [79]:
model.metrics_names

['loss', 'acc']

In [80]:
print(confusion_matrix(y_test,predictions))

[[772  18  82  11   3   7   3   5  74  25]
 [ 33 770  11   2   0   4   7   0  73 100]
 [ 84   5 656  31  41  85  33  19  34  12]
 [ 61  18 147 333  35 234  59  31  52  30]
 [ 74   7 172  54 476  81  52  36  37  11]
 [ 46  10 110 114  24 583  25  37  29  22]
 [ 23  10  87  43  24  45 701  10  39  18]
 [ 52   4  77  36  59 105   7 611  19  30]
 [ 81  16  18   2   1  10   5   0 837  30]
 [ 53  69  16  16   2   7   2   6  60 769]]


In [81]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.60      0.77      0.68      1000
           1       0.83      0.77      0.80      1000
           2       0.48      0.66      0.55      1000
           3       0.52      0.33      0.41      1000
           4       0.72      0.48      0.57      1000
           5       0.50      0.58      0.54      1000
           6       0.78      0.70      0.74      1000
           7       0.81      0.61      0.70      1000
           8       0.67      0.84      0.74      1000
           9       0.73      0.77      0.75      1000

   micro avg       0.65      0.65      0.65     10000
   macro avg       0.66      0.65      0.65     10000
weighted avg       0.66      0.65      0.65     10000

